namespace CEXIO.Api.MarketEntities
{
    public enum Symbols
    {
        BTC,
        USD,
        EUR,
        ETH,
        RUB,
        GBP,
        GHS,
        BCH,
        DASH,
        XRP,
        ZEC,
        BTG,
        XLM,
        QASH,
        GUSD
    }

    public enum SymbolPairs
    {
        BTC_USD,
        BTC_EUR,
        BTC_GBP,
        BTC_RUB,
        ETH_BTC,
        ETH_USD,
        ETH_EUR,
        GHS_BTC,
        BCH_USD,
        BCH_EUR,
        BCH_GBP,
        BCH_BTC,
        DASH_USD,
        DASH_EUR,
        DASH_GBP,
        DASH_BTC,
        XRP_USD,
        XRP_EUR,
        XRP_BTC,
        XLM_USD,
        XLM_EUR,
        XLM_BTC,
        ZEC_USD,
        ZEC_EUR,
        ZEC_GBP,
        ZEC_BTC,
        BTG_USD,
        BTG_EUR,
        BTG_BTC,
        QASH_BTC,
        QASH_ETH,
        GUSD_USD,
        GUSD_EUR
    }
}
